In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy 
print('i am learning numpy')
my_array=numpy.array([1,2,3,4])
my_list=['apple','watermelon','melon','orange']
print(my_array)
print(my_list)
print(type(my_array))
print(type(my_list))


i am learning numpy
[1 2 3 4]
['apple', 'watermelon', 'melon', 'orange']
<class 'numpy.ndarray'>
<class 'list'>


In [16]:
empty_array=numpy.array([1,1.1])
my_list=[1,'raj',1.1]
print(empty_array)
print(my_list)

[1.  1.1]
[1, 'raj', 1.1]


In [26]:
empty_array=numpy.array([[1,1.1]])
print(empty_array.shape)
print(empty_array.dtype)
print(empty_array.ndim)

(1, 2)
float64
2


In [8]:

import numpy as np
arr=np.array([1,2,3,4,5])
arr1=np.ones((3,3))
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
arr2=np.zeros((3,3))
print(arr2)
arr3=np.eye(3)
print(arr3)
print(arr3.ndim)

TypeError: Cannot interpret '3' as a data type

In [23]:
arr4=np.array([1,2,3,4,5],dtype='str')
arr5=np.array(['a','b'],dtype='U')
print(arr5)




['a' 'b']


In [25]:
my_arr=np.array([1,2,3,4,5])
print(my_arr[1])

2


In [28]:

import random
num = random.randrange(1, 10) 
print(num)

5


In [4]:
import random
num = random.randrange(1,10)
print(num)
print('choose no between 1 to 10')
for i in range(1,4):
    num1=int(input('enter the 1st number'))
    print('no. selected:',num1)
    
    print('no.from random:',num)
    if num==num1:
        print('you won')
        break
    else:
        print('you lose')    





6
choose no between 1 to 10
no. selected: 6
no.from random: 6
you won
